import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# Page Configuration
st.set_page_config(
    page_title="Smart Meter Analytics Dashboard",
    page_icon=" ",
    layout="wide",
    initial_sidebar_state="expanded",
)

TAMPERED_DEMO_METER_IDS = [1000, 1001]  # must match ingestion.py's default n_tamper_events=2

#1. LOAD PRE-COMPUTED PIPELINE OUTPUTS
@st.cache_data
def load_pipeline_data():
    raw_df = pd.read_csv("data/raw/cer_raw_data.csv")
    raw_df["timestamp"] = pd.to_datetime(raw_df["timestamp"])

    analytics_df = pd.read_csv("data/processed/cer_final_analytics.csv")
    return raw_df, analytics_df


try:
    raw_df, analytics_df = load_pipeline_data()
except FileNotFoundError:
    st.error(
        "Data files not found. Please run `python main.py` first to generate analytics!"
    )
    st.stop()

# Staleness guard: if the CSV on disk predates the current pipeline code,
# fail with one clear message instead of a raw KeyError deep in the page.
REQUIRED_ANALYTICS_COLS = ["silhouette_score", "is_anomaly", "cluster", "mean_kwh"]
missing_cols = [c for c in REQUIRED_ANALYTICS_COLS if c not in analytics_df.columns]
if missing_cols:
    st.error(
        f"'data/processed/cer_final_analytics.csv' is missing required column(s): {missing_cols}.\n\n"
        "This means the file on disk was generated by an older version of the pipeline "
        "(segmentation.py / anomaly.py). Run `python main.py` to regenerate it with the "
        "current code, then click 'Reload pipeline output from disk' in the sidebar."
    )
    st.stop()

# Merge time-series data with calculated clusters & anomaly flags
merged_df = raw_df.merge(
    analytics_df[["meter_id", "cluster", "is_anomaly"]], on="meter_id"
)


#SIDEBAR CONTROLS

st.sidebar.title("Grid Analytics Panel")
st.sidebar.markdown(
    "Irish CER Smart Metering Trial Dataset Processor for Load Profiling & Loss Detection."
)

if st.sidebar.button("Reload pipeline output from disk"):
    st.cache_data.clear()
    st.rerun()

st.sidebar.divider()
st.sidebar.subheader("Demo: Injected Tamper Event")
st.sidebar.caption(
    f"Runs the full pipeline with a known ground-truth tamper event injected into meters "
    f"{TAMPERED_DEMO_METER_IDS} (consumption drops to near-zero halfway through the window), "
    f"then checks whether the anomaly detector actually caught it."
)
if st.sidebar.button("Run pipeline WITH injected tamper event"):
    with st.spinner("Regenerating dataset with injected tamper event and re-running full pipeline..."):
        from main import run_pipeline
        result_df = run_pipeline(
            num_meters=50, days=14,
            inject_tamper_events=True, force_regenerate=True,
        )
    st.cache_data.clear()
    tampered_result = result_df[result_df["meter_id"].isin(TAMPERED_DEMO_METER_IDS)]
    all_caught = bool(tampered_result["is_anomaly"].all())
    if all_caught:
        st.sidebar.success(f"Both injected tamper meters {TAMPERED_DEMO_METER_IDS} were correctly flagged as anomalies.")
    else:
        missed = tampered_result[~tampered_result["is_anomaly"]]["meter_id"].tolist()
        st.sidebar.warning(f"Meter(s) {missed} were NOT flagged - check contamination rate or feature set.")
    st.rerun()

st.sidebar.divider()

selected_cluster = st.sidebar.multiselect(
    "Filter by Customer Cluster",
    options=sorted(analytics_df["cluster"].unique()),
    default=sorted(analytics_df["cluster"].unique()),
)

show_anomalies_only = st.sidebar.checkbox("Show Flagged Anomalies Only", False)

# Filter analytics data based on sidebar
filtered_df = analytics_df[analytics_df["cluster"].isin(selected_cluster)]
if show_anomalies_only:
    filtered_df = filtered_df[filtered_df["is_anomaly"]]

#HEADER & KPI CARDS
st.title("Smart Meter Data Analytics Dashboard")
st.caption("End-to-End Grid Quality & Customer Load Profiling System")

# If the currently-loaded data includes the known demo tamper IDs, show a
# banner confirming whether they were actually caught - makes the "before
# vs after" story visible right on the main page, not just in the sidebar.
if set(TAMPERED_DEMO_METER_IDS).issubset(set(analytics_df["meter_id"])):
    demo_rows = analytics_df[analytics_df["meter_id"].isin(TAMPERED_DEMO_METER_IDS)]
    if demo_rows["is_anomaly"].all():
        st.success(
            f"Demo mode active: meters {TAMPERED_DEMO_METER_IDS} have an injected tamper event "
            f"(consumption drop to near-zero halfway through the window) — **both correctly flagged** "
            f"as anomalies by the temporal features (half_period_ratio, daily_consumption_std)."
        )
    elif demo_rows["is_anomaly"].any():
        caught = demo_rows[demo_rows["is_anomaly"]]["meter_id"].tolist()
        missed = demo_rows[~demo_rows["is_anomaly"]]["meter_id"].tolist()
        st.warning(f"Demo mode active: caught {caught}, missed {missed} — inspect their half_period_ratio in the Anomaly tab.")

col1, col2, col3, col4 = st.columns(4)
col1.metric("Active Meters Displayed", len(filtered_df))
col2.metric("Total Energy Logged", f"{raw_df['kwh'].sum():,.1f} kWh")
col3.metric(
    "Flagged Anomalies",
    f"{analytics_df['is_anomaly'].sum()} Meters",
    delta=f"{(analytics_df['is_anomaly'].mean() * 100):.1f}% Rate",
    delta_color="inverse",
)
col4.metric("Clustering Silhouette Score", f"{analytics_df['silhouette_score'].iloc[0]:.4f}")

st.divider()
#DASHBOARD TABS
tab1, tab2, tab3 = st.tabs(
    [
        "Customer Load Profiling",
        "Anomaly & Theft Flagging",
        "Single Meter Drill-Down",
    ]
)

# TAB 1: CLUSTER PROFILING
with tab1:
    st.subheader("24-Hour Diurnal Load Profile by Cluster")

    merged_df["hour"] = merged_df["timestamp"].dt.hour
    cluster_profiles = (
        merged_df.groupby(["cluster", "hour"])["kwh"].mean().reset_index()
    )

    fig_cluster = px.line(
        cluster_profiles,
        x="hour",
        y="kwh",
        color="cluster",
        labels={"kwh": "Mean Consumption (kWh)", "hour": "Hour of Day"},
        title="Average Daily Load Curves",
        markers=True,
    )
    fig_cluster.update_layout(xaxis=dict(tickmode="linear", tick0=0, dtick=2))
    st.plotly_chart(fig_cluster, use_container_width=True)

    col_a, col_b = st.columns(2)
    with col_a:
        st.markdown("##### Cluster Summary Table")
        summary_table = filtered_df.groupby("cluster")[
            ["mean_kwh", "load_factor", "night_ratio"]
        ].mean()
        st.dataframe(
            summary_table.style.highlight_max(axis=0), use_container_width=True
        )

    with col_b:
        st.markdown("##### Load Factor vs Mean Load")
        fig_scatter = px.scatter(
            filtered_df,
            x="load_factor",
            y="mean_kwh",
            color="cluster",
            symbol="is_anomaly",
            labels={
                "mean_kwh": "Mean kWh / Interval",
                "load_factor": "Load Factor",
            },
        )
        st.plotly_chart(fig_scatter, use_container_width=True)

# TAB 2: ANOMALY DETECTION
with tab2:
    st.subheader("Flagged Meters (Suspected Bypass Theft or Faults)")

    anom_meters = analytics_df[analytics_df["is_anomaly"]]
    display_cols = ["meter_id", "cluster", "mean_kwh", "max_kwh", "load_factor", "night_ratio"]
    if "half_period_ratio" in anom_meters.columns:
        display_cols += ["half_period_ratio", "daily_consumption_std"]
    st.dataframe(anom_meters[display_cols], use_container_width=True)

    if not anom_meters.empty:
        selected_anom_id = st.selectbox(
            "Select Flagged Meter ID to Inspect Time Series:",
            anom_meters["meter_id"].tolist(),
        )

        meter_ts = merged_df[merged_df["meter_id"] == selected_anom_id]

        fig_anom = px.line(
            meter_ts,
            x="timestamp",
            y="kwh",
            title=f"Consumption Profile for Flagged Meter #{selected_anom_id}",
        )
        fig_anom.update_traces(line_color="crimson")
        st.plotly_chart(fig_anom, use_container_width=True)

        if selected_anom_id in TAMPERED_DEMO_METER_IDS:
            st.caption(
                f"This is a known-injected demo tamper event — consumption should show a "
                f"clean, regular pattern for the first half of the window, then drop to near-zero."
            )

# TAB 3: SINGLE METER DRILL-DOWN
with tab3:
    st.subheader("Individual Meter Deep-Dive")

    meter_choice = st.selectbox(
        "Choose Meter ID:", analytics_df["meter_id"].tolist()
    )
    m_info = analytics_df[analytics_df["meter_id"] == meter_choice].iloc[0]

    c1, c2, c3 = st.columns(3)
    c1.metric("Assigned Cluster", f"Cluster {int(m_info['cluster'])}")
    c2.metric("Mean Load", f"{m_info['mean_kwh']:.4f} kWh")
    c3.metric(
        "Status",
        "ANOMALOUS" if m_info["is_anomaly"] else "NORMAL",
        delta_color="inverse",
    )

    single_ts = merged_df[merged_df["meter_id"] == meter_choice]

    fig_single = px.line(
        single_ts,
        x="timestamp",
        y="kwh",
        title=f"Historical Consumption Profile — Meter #{meter_choice}",
    )
    st.plotly_chart(fig_single, use_container_width=True)
    
