import sys

import pandas as pd

from src.anomaly import detect_meter_anomalies
from src.segmentation import CLUSTER_FEATURE_COLS

# 1. Load the segmented dataset from Step 3
segmented_df = pd.read_csv("data/processed/cer_segmented.csv")

REQUIRED_SEGMENTED_COLS = CLUSTER_FEATURE_COLS + [
    "half_period_ratio", "daily_consumption_std", "cluster",
]

missing = [c for c in REQUIRED_SEGMENTED_COLS if c not in segmented_df.columns]
if missing:
    print(f"'data/processed/cer_segmented.csv' is missing required column(s): {missing}")
    print("  This usually means it was generated by an older version of features.py/segmentation.py.")
    print("  Fix: re-run the full chain in order, then re-run this script:")
    print("    python test_ingestion.py")
    print("    python test_features.py")
    print("    python test_segmentation.py")
    sys.exit(1)

# 2. Run anomaly detection
results_df, iso_model = detect_meter_anomalies(
    segmented_df, contamination=0.05
)

# 3. Save final analytics output
results_df.to_csv("data/processed/cer_final_analytics.csv", index=False)

# 4. Print flagged meters
print("\nFlagged Anomalous Meters Summary:")
flagged = results_df[results_df["is_anomaly"]]
print(
    flagged[
        ["meter_id", "cluster", "mean_kwh", "load_factor", "is_anomaly"]
    ].head()
)
