import sys
import pandas as pd
from src.segmentation import train_customer_clusters

# Load the features
feature_df = pd.read_csv("data/processed/cer_features.csv")
REQUIRED_FEATURE_COLS = ["mean_kwh", "load_factor", "night_ratio", "morn_peak_ratio", "eve_peak_ratio"]
missing = [c for c in REQUIRED_FEATURE_COLS if c not in feature_df.columns]
if missing:
    print(f"'data/processed/cer_features.csv' is missing required column(s): {missing}")
    print("   This usually means it was generated by an older version of src/features.py.")
    print("   Fix: re-run `python test_features.py` to regenerate it, then re-run this script.")
    sys.exit(1)

#Train customer clustering model
segmented_df, kmeans_model, scaler = train_customer_clusters(
    feature_df, n_clusters=3
)

#Save output with assigned cluster labels
segmented_df.to_csv("data/processed/cer_segmented.csv", index=False)

# View cluster assignments
print("\nSegmented Customers Sample:")
print(
    segmented_df[
        ["meter_id", "cluster", "mean_kwh", "night_ratio", "eve_peak_ratio"]
    ].head(10)
)
